#!/bin/bash
# Generate dependabot.yml from image directories
# This script discovers all container image directories and generates
# the Docker ecosystem entries for dependabot.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPENDABOT_FILE="$REPO_ROOT/.github/dependabot.yml"

# Find all image directories (those with metadata.yaml)
mapfile -t IMAGE_DIRS < <(find "$REPO_ROOT" -maxdepth 2 -name 'metadata.yaml' -type f | \
    sed "s|$REPO_ROOT/||" | \
    cut -d'/' -f1 | \
    sort -u)

# Generate the dependabot.yml content
cat > "$DEPENDABOT_FILE" << 'EOF'
---
# DO NOT EDIT - This file is auto-generated by .github/scripts/generate-dependabot.sh
# To add or modify entries, edit the script and run: pre-commit run generate-dependabot
version: 2
updates:
  # Devcontainer features
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily

  # GitHub Actions (SHA-pinned)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"

EOF

# Add docker entries for each image directory
for dir in "${IMAGE_DIRS[@]}"; do
    # Skip hidden directories and common non-image directories
    if [[ "$dir" == .* ]] || [[ "$dir" == "node_modules" ]]; then
        continue
    fi

    # Only add Docker ecosystem entry if a Dockerfile exists
    # Upstream-sourced images (no local Dockerfile) are skipped
    if [[ -f "$REPO_ROOT/$dir/Dockerfile" ]]; then
        cat >> "$DEPENDABOT_FILE" << EOF
  # Docker base images for $dir
  - package-ecosystem: "docker"
    directory: "/$dir"
    schedule:
      interval: daily

EOF
    fi
done

# Add devcontainers entries for images with devcontainer.json in assets
for dir in "${IMAGE_DIRS[@]}"; do
    if [[ -f "$REPO_ROOT/$dir/assets/devcontainer.json" ]]; then
        cat >> "$DEPENDABOT_FILE" << EOF
  # Devcontainer features for $dir
  - package-ecosystem: "devcontainers"
    directory: "/$dir/assets"
    schedule:
      interval: daily

EOF
    fi
done

# Add npm packages entry
cat >> "$DEPENDABOT_FILE" << 'EOF'
  # npm packages in devcontainer
  - package-ecosystem: "npm"
    directory: "/.devcontainer"
    schedule:
      interval: daily
EOF

echo "Generated $DEPENDABOT_FILE with entries for: ${IMAGE_DIRS[*]}"
