---
# Path-specific trivy ignores
# https://trivy.dev/latest/docs/configuration/filtering

vulnerabilities:

secrets:

misconfigurations:
  # chrony requires root for socket init, drops to chrony user via -u flag
  - id: AVD-DS-0002
    paths:
      - chrony/Dockerfile
  # Test fixtures are minimal and don't need production-grade security
  - id: AVD-DS-0001
    paths:
      - test-images/**/Dockerfile
  - id: AVD-DS-0002
    paths:
      - test-images/**/Dockerfile
  - id: AVD-DS-0026
    paths:
      - test-images/**/Dockerfile
  # HEALTHCHECK not applicable for interactive dev containers
  - id: AVD-DS-0026
    paths:
      - gastown-dev/Dockerfile
  # Go source includes internal Dockerfiles that don't need USER - not our code
  - id: AVD-DS-0002
    paths:
      - "**/go/src/**"
