---
# Path-specific trivy ignores
# https://trivy.dev/latest/docs/configuration/filtering

vulnerabilities:
  # firemerge: DoS via Range header merging in starlette
  # Risk accepted: behind Authentik forward proxy auth, single user
  # Fixed in starlette 0.49.1, pending upstream update
  - id: CVE-2025-62727
    paths:
      - firemerge

misconfigurations:
