---
# Path-specific trivy ignores
# https://trivy.dev/latest/docs/configuration/filtering

vulnerabilities:

misconfigurations:
  # chrony requires root for socket init, drops to chrony user via -u flag
  - id: AVD-DS-0002
    paths:
      - chrony/Dockerfile
  # Test fixtures are minimal and don't need production-grade security
  - id: AVD-DS-0001
    paths:
      - test-images/**/Dockerfile
  - id: AVD-DS-0002
    paths:
      - test-images/**/Dockerfile
  - id: AVD-DS-0026
    paths:
      - test-images/**/Dockerfile
