---
# Path-specific trivy ignores
# https://trivy.dev/latest/docs/configuration/filtering

vulnerabilities:
  # Go stdlib CVEs in third-party CLI tools (flux, talosctl, cilium, etc.)
  # These are compiled into upstream binaries - we can't fix without new releases
  # Scoped to gastown-dev image only
  - id: CVE-2022-24675
    paths: ["gastown-dev/**"]
  - id: CVE-2022-27664
    paths: ["gastown-dev/**"]
  - id: CVE-2022-28131
    paths: ["gastown-dev/**"]
  - id: CVE-2022-28327
    paths: ["gastown-dev/**"]
  - id: CVE-2022-2879
    paths: ["gastown-dev/**"]
  - id: CVE-2022-2880
    paths: ["gastown-dev/**"]
  - id: CVE-2022-29804
    paths: ["gastown-dev/**"]
  - id: CVE-2022-30580
    paths: ["gastown-dev/**"]
  - id: CVE-2022-30630
    paths: ["gastown-dev/**"]
  - id: CVE-2022-30631
    paths: ["gastown-dev/**"]
  - id: CVE-2022-30632
    paths: ["gastown-dev/**"]
  - id: CVE-2022-30633
    paths: ["gastown-dev/**"]
  - id: CVE-2022-30634
    paths: ["gastown-dev/**"]
  - id: CVE-2022-30635
    paths: ["gastown-dev/**"]
  - id: CVE-2022-32189
    paths: ["gastown-dev/**"]
  - id: CVE-2022-41715
    paths: ["gastown-dev/**"]
  - id: CVE-2022-41716
    paths: ["gastown-dev/**"]
  - id: CVE-2022-41720
    paths: ["gastown-dev/**"]
  - id: CVE-2022-41722
    paths: ["gastown-dev/**"]
  - id: CVE-2022-41723
    paths: ["gastown-dev/**"]
  - id: CVE-2022-41724
    paths: ["gastown-dev/**"]
  - id: CVE-2022-41725
    paths: ["gastown-dev/**"]
  - id: CVE-2023-24534
    paths: ["gastown-dev/**"]
  - id: CVE-2023-24536
    paths: ["gastown-dev/**"]
  - id: CVE-2023-24537
    paths: ["gastown-dev/**"]
  - id: CVE-2023-24538
    paths: ["gastown-dev/**"]
  - id: CVE-2023-24539
    paths: ["gastown-dev/**"]
  - id: CVE-2023-24540
    paths: ["gastown-dev/**"]
  - id: CVE-2023-29400
    paths: ["gastown-dev/**"]
  - id: CVE-2023-29403
    paths: ["gastown-dev/**"]
  - id: CVE-2023-39321
    paths: ["gastown-dev/**"]
  - id: CVE-2023-39322
    paths: ["gastown-dev/**"]
  - id: CVE-2023-39325
    paths: ["gastown-dev/**"]
  - id: CVE-2023-44487
    paths: ["gastown-dev/**"]
  - id: CVE-2023-45283
    paths: ["gastown-dev/**"]
  - id: CVE-2023-45287
    paths: ["gastown-dev/**"]
  - id: CVE-2023-45288
    paths: ["gastown-dev/**"]
  - id: CVE-2024-24790
    paths: ["gastown-dev/**"]
  - id: CVE-2024-25621
    paths: ["gastown-dev/**"]
  - id: CVE-2024-34156
    paths: ["gastown-dev/**"]
  - id: CVE-2024-52308
    paths: ["gastown-dev/**"]
  - id: CVE-2025-22874
    paths: ["gastown-dev/**"]
  - id: CVE-2025-47907
    paths: ["gastown-dev/**"]
  - id: CVE-2025-53547
    paths: ["gastown-dev/**"]
  - id: CVE-2025-58183
    paths: ["gastown-dev/**"]
  - id: CVE-2025-61729
    paths: ["gastown-dev/**"]
  - id: CVE-2025-64756
    paths: ["gastown-dev/**"]
  - id: CVE-2025-66506
    paths: ["gastown-dev/**"]
  - id: CVE-2025-66564
    paths: ["gastown-dev/**"]

secrets:
  # safe-chain creates CA certs for MITM proxy to protect npm/pip installs
  - id: private-key
    paths:
      - "**/safe-chain/certs/**"

misconfigurations:
  # chrony requires root for socket init, drops to chrony user via -u flag
  - id: AVD-DS-0002
    paths:
      - chrony/Dockerfile
  # Test fixtures are minimal and don't need production-grade security
  - id: AVD-DS-0001
    paths:
      - test-images/**/Dockerfile
  - id: AVD-DS-0002
    paths:
      - test-images/**/Dockerfile
  - id: AVD-DS-0026
    paths:
      - test-images/**/Dockerfile
  # HEALTHCHECK not applicable for interactive dev containers
  - id: AVD-DS-0026
    paths:
      - gastown-dev/Dockerfile
  # Go source includes internal Dockerfiles that don't need USER - not our code
  - id: AVD-DS-0002
    paths:
      - "**/go/src/**"
