---
# Path-specific trivy ignores
# https://trivy.dev/latest/docs/configuration/filtering

vulnerabilities:

misconfigurations:
  # chrony requires root for socket init, drops to chrony user via -u flag
  - id: AVD-DS-0002
    paths:
      - chrony/Dockerfile
