#!/bin/sh
# Chrony NTP Server Startup Script
# Generates chrony.conf and starts chronyd

set -e

# Configuration defaults
NTP_SERVERS="${NTP_SERVERS:-time.cloudflare.com}"
NTP_PORT="${NTP_PORT:-1123}"
LOG_LEVEL="${LOG_LEVEL:-0}"
ENABLE_NTS="${ENABLE_NTS:-false}"
NOCLIENTLOG="${NOCLIENTLOG:-false}"

# Input validation (security: prevent injection attacks)
if ! echo "$LOG_LEVEL" | grep -qE '^[0-3]$'; then
    echo "ERROR: LOG_LEVEL must be 0-3, got: $LOG_LEVEL" >&2
    exit 1
fi

if ! echo "$NTP_PORT" | grep -qE '^[0-9]+$'; then
    echo "ERROR: NTP_PORT must be numeric, got: $NTP_PORT" >&2
    exit 1
fi

if [ "$NTP_PORT" -lt 1 ] || [ "$NTP_PORT" -gt 65535 ]; then
    echo "ERROR: NTP_PORT must be 1-65535, got: $NTP_PORT" >&2
    exit 1
fi

# Configuration paths (writable locations)
CHRONY_CONF="/var/lib/chrony/chrony.conf"
CHRONY_DRIFT="/var/lib/chrony/drift"

# Ensure runtime directories exist with correct permissions
# /run is tmpfs and resets on container start
mkdir -p /run/chrony
chown chrony:chrony /run/chrony
chmod 750 /run/chrony

# Generate chrony.conf
cat > "${CHRONY_CONF}" << EOF
# Chrony configuration - auto-generated by startup.sh
# Do not edit manually

# Drift file
driftfile ${CHRONY_DRIFT}

# NTP port (high port for unprivileged operation)
port ${NTP_PORT}

# Allow all clients
allow all

# Step the clock if offset is large (first 3 updates only)
makestep 1.0 3

EOF

# Add NTP servers
IFS=','
for server in ${NTP_SERVERS}; do
    server=$(echo "${server}" | xargs) # trim whitespace
    if [ -n "${server}" ]; then
        # Validate server name (hostname or IP format, security: prevent config injection)
        if ! echo "$server" | grep -qE '^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$'; then
            echo "WARNING: Invalid server name format: $server (skipping)" >&2
            continue
        fi
        if [ "${ENABLE_NTS}" = "true" ]; then
            echo "server ${server} iburst nts" >> "${CHRONY_CONF}"
        else
            echo "server ${server} iburst" >> "${CHRONY_CONF}"
        fi
    fi
done
unset IFS

# Add noclientlog if enabled
if [ "${NOCLIENTLOG}" = "true" ]; then
    echo "noclientlog" >> "${CHRONY_CONF}"
fi

# Log configuration on startup
echo "Starting chronyd with configuration:"
echo "  NTP_SERVERS: ${NTP_SERVERS}"
echo "  NTP_PORT: ${NTP_PORT}"
echo "  ENABLE_NTS: ${ENABLE_NTS}"
echo "  LOG_LEVEL: ${LOG_LEVEL}"

# Start chronyd
# -d: Run in foreground (don't daemonize)
# -u: Drop to chrony user after initialization
# -x: Don't control system clock (no SYS_TIME capability needed)
# -f: Configuration file
# -L: Log level (0=info, 1=warn, 2=error, 3=fatal)
exec /usr/sbin/chronyd -d -u chrony -x -f "${CHRONY_CONF}" -L "${LOG_LEVEL}"
